/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AdminAdoptionRouteImport } from './routes/admin/adoption'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminEmailRouteImport } from './routes/admin/email'
import { Route as AdminReadinessRouteImport } from './routes/admin/readiness'
import { Route as AdminStoreRouteImport } from './routes/admin/store'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSplatRouteImport } from './routes/dashboard/$'
import { Route as DashboardAiAssistantRouteImport } from './routes/dashboard/ai-assistant'
import { Route as DashboardAiGovernanceRouteImport } from './routes/dashboard/ai-governance'
import { Route as DashboardAuditBinderRouteImport } from './routes/dashboard/audit-binder'
import { Route as DashboardNetworkRouteImport } from './routes/dashboard/network'
import { Route as DashboardPdsaLabRouteImport } from './routes/dashboard/pdsa-lab'
import { Route as DashboardPlaybooksRouteImport } from './routes/dashboard/playbooks'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardStaffTasksRouteImport } from './routes/dashboard/staff-tasks'
import { Route as FeaturesIndexRouteImport } from './routes/features/index'
import { Route as FeaturesHrsaAuditBinderRouteImport } from './routes/features/hrsa-audit-binder'
import { Route as FeaturesPcmhEvidenceRouteImport } from './routes/features/pcmh-evidence'
import { Route as FeaturesPdsaCycleManagerRouteImport } from './routes/features/pdsa-cycle-manager'
import { Route as FeaturesSpcChartsRouteImport } from './routes/features/spc-charts'
import { Route as FeaturesUdsTrackingRouteImport } from './routes/features/uds-tracking'
import { Route as ForOperationsManagersRouteImport } from './routes/for.operations-managers'
import { Route as ForPcmhCoordinatorsRouteImport } from './routes/for.pcmh-coordinators'
import { Route as ForQiDirectorsRouteImport } from './routes/for.qi-directors'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ManualIndexRouteImport } from './routes/manual/index'
import { Route as ManualThankYouRouteImport } from './routes/manual/thank-you'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as StoreSlugRouteImport } from './routes/store/$slug'
import { Route as StoreSuccessRouteImport } from './routes/store/success'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AdminAccountOrgIdRouteImport } from './routes/admin/account.$orgId'
import { Route as DashboardQiReportsIndexRouteImport } from './routes/dashboard/qi-reports/index'
import { Route as DashboardQiReportsIdRouteImport } from './routes/dashboard/qi-reports/$id'
import { Route as DashboardQiReportsNewRouteImport } from './routes/dashboard/qi-reports/new'
import { Route as StoreBundleSlugRouteImport } from './routes/store/bundle.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdoptionRoute = AdminAdoptionRouteImport.update({
  id: '/adoption',
  path: '/adoption',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailRoute = AdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReadinessRoute = AdminReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStoreRoute = AdminStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSplatRoute = DashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAiAssistantRoute = DashboardAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAiGovernanceRoute = DashboardAiGovernanceRouteImport.update({
  id: '/ai-governance',
  path: '/ai-governance',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAuditBinderRoute = DashboardAuditBinderRouteImport.update({
  id: '/audit-binder',
  path: '/audit-binder',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNetworkRoute = DashboardNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPdsaLabRoute = DashboardPdsaLabRouteImport.update({
  id: '/pdsa-lab',
  path: '/pdsa-lab',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlaybooksRoute = DashboardPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStaffTasksRoute = DashboardStaffTasksRouteImport.update({
  id: '/staff-tasks',
  path: '/staff-tasks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesHrsaAuditBinderRoute = FeaturesHrsaAuditBinderRouteImport.update({
  id: '/features/hrsa-audit-binder',
  path: '/features/hrsa-audit-binder',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesPcmhEvidenceRoute = FeaturesPcmhEvidenceRouteImport.update({
  id: '/features/pcmh-evidence',
  path: '/features/pcmh-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesPdsaCycleManagerRoute =
  FeaturesPdsaCycleManagerRouteImport.update({
    id: '/features/pdsa-cycle-manager',
    path: '/features/pdsa-cycle-manager',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesSpcChartsRoute = FeaturesSpcChartsRouteImport.update({
  id: '/features/spc-charts',
  path: '/features/spc-charts',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesUdsTrackingRoute = FeaturesUdsTrackingRouteImport.update({
  id: '/features/uds-tracking',
  path: '/features/uds-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOperationsManagersRoute = ForOperationsManagersRouteImport.update({
  id: '/for/operations-managers',
  path: '/for/operations-managers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPcmhCoordinatorsRoute = ForPcmhCoordinatorsRouteImport.update({
  id: '/for/pcmh-coordinators',
  path: '/for/pcmh-coordinators',
  getParentRoute: () => rootRouteImport,
} as any)
const ForQiDirectorsRoute = ForQiDirectorsRouteImport.update({
  id: '/for/qi-directors',
  path: '/for/qi-directors',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualIndexRoute = ManualIndexRouteImport.update({
  id: '/manual/',
  path: '/manual/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualThankYouRoute = ManualThankYouRouteImport.update({
  id: '/manual/thank-you',
  path: '/manual/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSuccessRoute = StoreSuccessRouteImport.update({
  id: '/store/success',
  path: '/store/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountOrgIdRoute = AdminAccountOrgIdRouteImport.update({
  id: '/account/$orgId',
  path: '/account/$orgId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardQiReportsIndexRoute = DashboardQiReportsIndexRouteImport.update({
  id: '/qi-reports/',
  path: '/qi-reports/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardQiReportsIdRoute = DashboardQiReportsIdRouteImport.update({
  id: '/qi-reports/$id',
  path: '/qi-reports/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardQiReportsNewRoute = DashboardQiReportsNewRouteImport.update({
  id: '/qi-reports/new',
  path: '/qi-reports/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const StoreBundleSlugRoute = StoreBundleSlugRouteImport.update({
  id: '/store/bundle/$slug',
  path: '/store/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/readiness': typeof ReadinessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/adoption': typeof AdminAdoptionRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/ai-governance': typeof DashboardAiGovernanceRoute
  '/dashboard/audit-binder': typeof DashboardAuditBinderRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/pdsa-lab': typeof DashboardPdsaLabRoute
  '/dashboard/playbooks': typeof DashboardPlaybooksRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/staff-tasks': typeof DashboardStaffTasksRoute
  '/features/hrsa-audit-binder': typeof FeaturesHrsaAuditBinderRoute
  '/features/pcmh-evidence': typeof FeaturesPcmhEvidenceRoute
  '/features/pdsa-cycle-manager': typeof FeaturesPdsaCycleManagerRoute
  '/features/spc-charts': typeof FeaturesSpcChartsRoute
  '/features/uds-tracking': typeof FeaturesUdsTrackingRoute
  '/for/operations-managers': typeof ForOperationsManagersRoute
  '/for/pcmh-coordinators': typeof ForPcmhCoordinatorsRoute
  '/for/qi-directors': typeof ForQiDirectorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manual/thank-you': typeof ManualThankYouRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/store/success': typeof StoreSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/manual/': typeof ManualIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/store/': typeof StoreIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/account/$orgId': typeof AdminAccountOrgIdRoute
  '/dashboard/qi-reports/$id': typeof DashboardQiReportsIdRoute
  '/dashboard/qi-reports/new': typeof DashboardQiReportsNewRoute
  '/store/bundle/$slug': typeof StoreBundleSlugRoute
  '/dashboard/qi-reports/': typeof DashboardQiReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/readiness': typeof ReadinessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/adoption': typeof AdminAdoptionRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/ai-governance': typeof DashboardAiGovernanceRoute
  '/dashboard/audit-binder': typeof DashboardAuditBinderRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/pdsa-lab': typeof DashboardPdsaLabRoute
  '/dashboard/playbooks': typeof DashboardPlaybooksRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/staff-tasks': typeof DashboardStaffTasksRoute
  '/features/hrsa-audit-binder': typeof FeaturesHrsaAuditBinderRoute
  '/features/pcmh-evidence': typeof FeaturesPcmhEvidenceRoute
  '/features/pdsa-cycle-manager': typeof FeaturesPdsaCycleManagerRoute
  '/features/spc-charts': typeof FeaturesSpcChartsRoute
  '/features/uds-tracking': typeof FeaturesUdsTrackingRoute
  '/for/operations-managers': typeof ForOperationsManagersRoute
  '/for/pcmh-coordinators': typeof ForPcmhCoordinatorsRoute
  '/for/qi-directors': typeof ForQiDirectorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manual/thank-you': typeof ManualThankYouRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/store/success': typeof StoreSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/manual': typeof ManualIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/store': typeof StoreIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/account/$orgId': typeof AdminAccountOrgIdRoute
  '/dashboard/qi-reports/$id': typeof DashboardQiReportsIdRoute
  '/dashboard/qi-reports/new': typeof DashboardQiReportsNewRoute
  '/store/bundle/$slug': typeof StoreBundleSlugRoute
  '/dashboard/qi-reports': typeof DashboardQiReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/readiness': typeof ReadinessRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/adoption': typeof AdminAdoptionRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/ai-governance': typeof DashboardAiGovernanceRoute
  '/dashboard/audit-binder': typeof DashboardAuditBinderRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/pdsa-lab': typeof DashboardPdsaLabRoute
  '/dashboard/playbooks': typeof DashboardPlaybooksRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/staff-tasks': typeof DashboardStaffTasksRoute
  '/features/hrsa-audit-binder': typeof FeaturesHrsaAuditBinderRoute
  '/features/pcmh-evidence': typeof FeaturesPcmhEvidenceRoute
  '/features/pdsa-cycle-manager': typeof FeaturesPdsaCycleManagerRoute
  '/features/spc-charts': typeof FeaturesSpcChartsRoute
  '/features/uds-tracking': typeof FeaturesUdsTrackingRoute
  '/for/operations-managers': typeof ForOperationsManagersRoute
  '/for/pcmh-coordinators': typeof ForPcmhCoordinatorsRoute
  '/for/qi-directors': typeof ForQiDirectorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manual/thank-you': typeof ManualThankYouRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/store/success': typeof StoreSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/manual/': typeof ManualIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/store/': typeof StoreIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/account/$orgId': typeof AdminAccountOrgIdRoute
  '/dashboard/qi-reports/$id': typeof DashboardQiReportsIdRoute
  '/dashboard/qi-reports/new': typeof DashboardQiReportsNewRoute
  '/store/bundle/$slug': typeof StoreBundleSlugRoute
  '/dashboard/qi-reports/': typeof DashboardQiReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/about'
    | '/auth'
    | '/contact'
    | '/demo'
    | '/how-it-works'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/readiness'
    | '/refund-policy'
    | '/reset-password'
    | '/security'
    | '/status'
    | '/terms'
    | '/admin/$'
    | '/admin/adoption'
    | '/admin/billing'
    | '/admin/email'
    | '/admin/readiness'
    | '/admin/store'
    | '/admin/users'
    | '/dashboard/$'
    | '/dashboard/ai-assistant'
    | '/dashboard/ai-governance'
    | '/dashboard/audit-binder'
    | '/dashboard/network'
    | '/dashboard/pdsa-lab'
    | '/dashboard/playbooks'
    | '/dashboard/settings'
    | '/dashboard/staff-tasks'
    | '/features/hrsa-audit-binder'
    | '/features/pcmh-evidence'
    | '/features/pdsa-cycle-manager'
    | '/features/spc-charts'
    | '/features/uds-tracking'
    | '/for/operations-managers'
    | '/for/pcmh-coordinators'
    | '/for/qi-directors'
    | '/invite/$token'
    | '/manual/thank-you'
    | '/resources/$slug'
    | '/store/$slug'
    | '/store/success'
    | '/admin/'
    | '/dashboard/'
    | '/features/'
    | '/manual/'
    | '/resources/'
    | '/store/'
    | '/.lovable/oauth/consent'
    | '/admin/account/$orgId'
    | '/dashboard/qi-reports/$id'
    | '/dashboard/qi-reports/new'
    | '/store/bundle/$slug'
    | '/dashboard/qi-reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/demo'
    | '/how-it-works'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/readiness'
    | '/refund-policy'
    | '/reset-password'
    | '/security'
    | '/status'
    | '/terms'
    | '/admin/$'
    | '/admin/adoption'
    | '/admin/billing'
    | '/admin/email'
    | '/admin/readiness'
    | '/admin/store'
    | '/admin/users'
    | '/dashboard/$'
    | '/dashboard/ai-assistant'
    | '/dashboard/ai-governance'
    | '/dashboard/audit-binder'
    | '/dashboard/network'
    | '/dashboard/pdsa-lab'
    | '/dashboard/playbooks'
    | '/dashboard/settings'
    | '/dashboard/staff-tasks'
    | '/features/hrsa-audit-binder'
    | '/features/pcmh-evidence'
    | '/features/pdsa-cycle-manager'
    | '/features/spc-charts'
    | '/features/uds-tracking'
    | '/for/operations-managers'
    | '/for/pcmh-coordinators'
    | '/for/qi-directors'
    | '/invite/$token'
    | '/manual/thank-you'
    | '/resources/$slug'
    | '/store/$slug'
    | '/store/success'
    | '/admin'
    | '/dashboard'
    | '/features'
    | '/manual'
    | '/resources'
    | '/store'
    | '/.lovable/oauth/consent'
    | '/admin/account/$orgId'
    | '/dashboard/qi-reports/$id'
    | '/dashboard/qi-reports/new'
    | '/store/bundle/$slug'
    | '/dashboard/qi-reports'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/about'
    | '/auth'
    | '/contact'
    | '/demo'
    | '/how-it-works'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/readiness'
    | '/refund-policy'
    | '/reset-password'
    | '/security'
    | '/status'
    | '/terms'
    | '/admin/$'
    | '/admin/adoption'
    | '/admin/billing'
    | '/admin/email'
    | '/admin/readiness'
    | '/admin/store'
    | '/admin/users'
    | '/dashboard/$'
    | '/dashboard/ai-assistant'
    | '/dashboard/ai-governance'
    | '/dashboard/audit-binder'
    | '/dashboard/network'
    | '/dashboard/pdsa-lab'
    | '/dashboard/playbooks'
    | '/dashboard/settings'
    | '/dashboard/staff-tasks'
    | '/features/hrsa-audit-binder'
    | '/features/pcmh-evidence'
    | '/features/pdsa-cycle-manager'
    | '/features/spc-charts'
    | '/features/uds-tracking'
    | '/for/operations-managers'
    | '/for/pcmh-coordinators'
    | '/for/qi-directors'
    | '/invite/$token'
    | '/manual/thank-you'
    | '/resources/$slug'
    | '/store/$slug'
    | '/store/success'
    | '/admin/'
    | '/dashboard/'
    | '/features/'
    | '/manual/'
    | '/resources/'
    | '/store/'
    | '/.lovable/oauth/consent'
    | '/admin/account/$orgId'
    | '/dashboard/qi-reports/$id'
    | '/dashboard/qi-reports/new'
    | '/store/bundle/$slug'
    | '/dashboard/qi-reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  HowItWorksRoute: typeof HowItWorksRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReadinessRoute: typeof ReadinessRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  FeaturesHrsaAuditBinderRoute: typeof FeaturesHrsaAuditBinderRoute
  FeaturesPcmhEvidenceRoute: typeof FeaturesPcmhEvidenceRoute
  FeaturesPdsaCycleManagerRoute: typeof FeaturesPdsaCycleManagerRoute
  FeaturesSpcChartsRoute: typeof FeaturesSpcChartsRoute
  FeaturesUdsTrackingRoute: typeof FeaturesUdsTrackingRoute
  ForOperationsManagersRoute: typeof ForOperationsManagersRoute
  ForPcmhCoordinatorsRoute: typeof ForPcmhCoordinatorsRoute
  ForQiDirectorsRoute: typeof ForQiDirectorsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ManualThankYouRoute: typeof ManualThankYouRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  StoreSlugRoute: typeof StoreSlugRoute
  StoreSuccessRoute: typeof StoreSuccessRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  ManualIndexRoute: typeof ManualIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  StoreBundleSlugRoute: typeof StoreBundleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/adoption': {
      id: '/admin/adoption'
      path: '/adoption'
      fullPath: '/admin/adoption'
      preLoaderRoute: typeof AdminAdoptionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email': {
      id: '/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AdminEmailRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/readiness': {
      id: '/admin/readiness'
      path: '/readiness'
      fullPath: '/admin/readiness'
      preLoaderRoute: typeof AdminReadinessRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/store': {
      id: '/admin/store'
      path: '/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AdminStoreRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$': {
      id: '/dashboard/$'
      path: '/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof DashboardSplatRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ai-assistant': {
      id: '/dashboard/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/dashboard/ai-assistant'
      preLoaderRoute: typeof DashboardAiAssistantRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ai-governance': {
      id: '/dashboard/ai-governance'
      path: '/ai-governance'
      fullPath: '/dashboard/ai-governance'
      preLoaderRoute: typeof DashboardAiGovernanceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/audit-binder': {
      id: '/dashboard/audit-binder'
      path: '/audit-binder'
      fullPath: '/dashboard/audit-binder'
      preLoaderRoute: typeof DashboardAuditBinderRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/network': {
      id: '/dashboard/network'
      path: '/network'
      fullPath: '/dashboard/network'
      preLoaderRoute: typeof DashboardNetworkRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pdsa-lab': {
      id: '/dashboard/pdsa-lab'
      path: '/pdsa-lab'
      fullPath: '/dashboard/pdsa-lab'
      preLoaderRoute: typeof DashboardPdsaLabRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/playbooks': {
      id: '/dashboard/playbooks'
      path: '/playbooks'
      fullPath: '/dashboard/playbooks'
      preLoaderRoute: typeof DashboardPlaybooksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/staff-tasks': {
      id: '/dashboard/staff-tasks'
      path: '/staff-tasks'
      fullPath: '/dashboard/staff-tasks'
      preLoaderRoute: typeof DashboardStaffTasksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/hrsa-audit-binder': {
      id: '/features/hrsa-audit-binder'
      path: '/features/hrsa-audit-binder'
      fullPath: '/features/hrsa-audit-binder'
      preLoaderRoute: typeof FeaturesHrsaAuditBinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/pcmh-evidence': {
      id: '/features/pcmh-evidence'
      path: '/features/pcmh-evidence'
      fullPath: '/features/pcmh-evidence'
      preLoaderRoute: typeof FeaturesPcmhEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/pdsa-cycle-manager': {
      id: '/features/pdsa-cycle-manager'
      path: '/features/pdsa-cycle-manager'
      fullPath: '/features/pdsa-cycle-manager'
      preLoaderRoute: typeof FeaturesPdsaCycleManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/spc-charts': {
      id: '/features/spc-charts'
      path: '/features/spc-charts'
      fullPath: '/features/spc-charts'
      preLoaderRoute: typeof FeaturesSpcChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/uds-tracking': {
      id: '/features/uds-tracking'
      path: '/features/uds-tracking'
      fullPath: '/features/uds-tracking'
      preLoaderRoute: typeof FeaturesUdsTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/operations-managers': {
      id: '/for/operations-managers'
      path: '/for/operations-managers'
      fullPath: '/for/operations-managers'
      preLoaderRoute: typeof ForOperationsManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/pcmh-coordinators': {
      id: '/for/pcmh-coordinators'
      path: '/for/pcmh-coordinators'
      fullPath: '/for/pcmh-coordinators'
      preLoaderRoute: typeof ForPcmhCoordinatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/qi-directors': {
      id: '/for/qi-directors'
      path: '/for/qi-directors'
      fullPath: '/for/qi-directors'
      preLoaderRoute: typeof ForQiDirectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual/': {
      id: '/manual/'
      path: '/manual'
      fullPath: '/manual/'
      preLoaderRoute: typeof ManualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual/thank-you': {
      id: '/manual/thank-you'
      path: '/manual/thank-you'
      fullPath: '/manual/thank-you'
      preLoaderRoute: typeof ManualThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/success': {
      id: '/store/success'
      path: '/store/success'
      fullPath: '/store/success'
      preLoaderRoute: typeof StoreSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account/$orgId': {
      id: '/admin/account/$orgId'
      path: '/account/$orgId'
      fullPath: '/admin/account/$orgId'
      preLoaderRoute: typeof AdminAccountOrgIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/qi-reports/': {
      id: '/dashboard/qi-reports/'
      path: '/qi-reports'
      fullPath: '/dashboard/qi-reports/'
      preLoaderRoute: typeof DashboardQiReportsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/qi-reports/$id': {
      id: '/dashboard/qi-reports/$id'
      path: '/qi-reports/$id'
      fullPath: '/dashboard/qi-reports/$id'
      preLoaderRoute: typeof DashboardQiReportsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/qi-reports/new': {
      id: '/dashboard/qi-reports/new'
      path: '/qi-reports/new'
      fullPath: '/dashboard/qi-reports/new'
      preLoaderRoute: typeof DashboardQiReportsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/store/bundle/$slug': {
      id: '/store/bundle/$slug'
      path: '/store/bundle/$slug'
      fullPath: '/store/bundle/$slug'
      preLoaderRoute: typeof StoreBundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminAdoptionRoute: typeof AdminAdoptionRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminEmailRoute: typeof AdminEmailRoute
  AdminReadinessRoute: typeof AdminReadinessRoute
  AdminStoreRoute: typeof AdminStoreRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAccountOrgIdRoute: typeof AdminAccountOrgIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminAdoptionRoute: AdminAdoptionRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminEmailRoute: AdminEmailRoute,
  AdminReadinessRoute: AdminReadinessRoute,
  AdminStoreRoute: AdminStoreRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAccountOrgIdRoute: AdminAccountOrgIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardSplatRoute: typeof DashboardSplatRoute
  DashboardAiAssistantRoute: typeof DashboardAiAssistantRoute
  DashboardAiGovernanceRoute: typeof DashboardAiGovernanceRoute
  DashboardAuditBinderRoute: typeof DashboardAuditBinderRoute
  DashboardNetworkRoute: typeof DashboardNetworkRoute
  DashboardPdsaLabRoute: typeof DashboardPdsaLabRoute
  DashboardPlaybooksRoute: typeof DashboardPlaybooksRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStaffTasksRoute: typeof DashboardStaffTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardQiReportsIdRoute: typeof DashboardQiReportsIdRoute
  DashboardQiReportsNewRoute: typeof DashboardQiReportsNewRoute
  DashboardQiReportsIndexRoute: typeof DashboardQiReportsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSplatRoute: DashboardSplatRoute,
  DashboardAiAssistantRoute: DashboardAiAssistantRoute,
  DashboardAiGovernanceRoute: DashboardAiGovernanceRoute,
  DashboardAuditBinderRoute: DashboardAuditBinderRoute,
  DashboardNetworkRoute: DashboardNetworkRoute,
  DashboardPdsaLabRoute: DashboardPdsaLabRoute,
  DashboardPlaybooksRoute: DashboardPlaybooksRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStaffTasksRoute: DashboardStaffTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardQiReportsIdRoute: DashboardQiReportsIdRoute,
  DashboardQiReportsNewRoute: DashboardQiReportsNewRoute,
  DashboardQiReportsIndexRoute: DashboardQiReportsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  HowItWorksRoute: HowItWorksRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReadinessRoute: ReadinessRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  FeaturesHrsaAuditBinderRoute: FeaturesHrsaAuditBinderRoute,
  FeaturesPcmhEvidenceRoute: FeaturesPcmhEvidenceRoute,
  FeaturesPdsaCycleManagerRoute: FeaturesPdsaCycleManagerRoute,
  FeaturesSpcChartsRoute: FeaturesSpcChartsRoute,
  FeaturesUdsTrackingRoute: FeaturesUdsTrackingRoute,
  ForOperationsManagersRoute: ForOperationsManagersRoute,
  ForPcmhCoordinatorsRoute: ForPcmhCoordinatorsRoute,
  ForQiDirectorsRoute: ForQiDirectorsRoute,
  InviteTokenRoute: InviteTokenRoute,
  ManualThankYouRoute: ManualThankYouRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  StoreSlugRoute: StoreSlugRoute,
  StoreSuccessRoute: StoreSuccessRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  ManualIndexRoute: ManualIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  StoreBundleSlugRoute: StoreBundleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
