// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's email, user id, and their MeasureWise organization (id, name, plan). Use to confirm authentication and current org context.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile, error: profileErr } = await supabase.from("profiles").select("organization_id, full_name").eq("id", userId).maybeSingle();
    if (profileErr) {
      return { content: [{ type: "text", text: profileErr.message }], isError: true };
    }
    let org = null;
    if (profile?.organization_id) {
      const { data: o } = await supabase.from("organizations").select("id, name").eq("id", profile.organization_id).maybeSingle();
      org = o ?? null;
    }
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail() ?? null,
      full_name: profile?.full_name ?? null,
      organization: org
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-pdsa-cycles.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pdsa_cycles_default = defineTool2({
  name: "list_pdsa_cycles",
  title: "List PDSA cycles",
  description: "List the signed-in user's organization's PDSA (Plan-Do-Study-Act) quality improvement cycles. Returns id, title/aim, phase, completeness score, and timestamps. Results are scoped by RLS to the caller's organization.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of cycles to return."),
    phase: z.enum(["plan", "do", "study", "act", "completed"]).optional().describe("Optional PDSA phase filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, phase }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let query = supabase.from("pdsa_cycles").select(
      "id, aim_statement, phase, completeness_score, improvement_pct, baseline_rate, created_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit);
    if (phase) query = query.eq("phase", phase);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { cycles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-pdsa-cycle.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_pdsa_cycle_default = defineTool3({
  name: "get_pdsa_cycle",
  title: "Get PDSA cycle",
  description: "Fetch full details of a single PDSA cycle by id (aim, intervention, predicted vs. actual outcome, analysis, next steps). Scoped by RLS to the caller's organization.",
  inputSchema: {
    id: z2.string().uuid().describe("PDSA cycle UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("pdsa_cycles").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "PDSA cycle not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { cycle: data }
    };
  }
});

// src/lib/mcp/tools/list-qi-reports.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_qi_reports_default = defineTool4({
  name: "list_qi_reports",
  title: "List QI reports",
  description: "List the caller's organization's Quality Improvement board/committee reports with id, title, status, and timestamps. Scoped by RLS.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("qi_reports").select("id, title, status, reporting_period_start, reporting_period_end, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eeyigxcwewdqfeidqbxk";
var mcp_default = defineMcp({
  name: "measurewise-mcp",
  title: "MeasureWise",
  version: "0.1.0",
  instructions: "MeasureWise tools for FQHC Quality Directors. Use `whoami` to confirm the signed-in user and organization. Use `list_pdsa_cycles` / `get_pdsa_cycle` to inspect Plan-Do-Study-Act quality improvement cycles. Use `list_qi_reports` to browse board / committee QI reports. All tools are scoped by RLS to the caller's organization.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_pdsa_cycles_default, get_pdsa_cycle_default, list_qi_reports_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
